name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore tests/GoogleAuthTests/GoogleAuthTests.csproj

    - name: Build
      run: dotnet build --no-restore tests/GoogleAuthTests/GoogleAuthTests.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal tests/GoogleAuthTests/GoogleAuthTests.csproj
